name: RykenSlimefunCustomizer
version: '${project.version}'
main: org.lins.mmmjjkx.rykenslimefuncustomizer.RykenSlimefunCustomizer
api-version: '1.18'
depend: [Slimefun]
softdepend:
  - GuizhanLibPlugin
  - SlimeGlue
  - ColoredEnderChests
  - DyedBackpacks
  - EnderCargo
  - EcoPower
  - ElectricSpawners
  - ExoticGarden
  - ExtraGear
  - ExtraHeads
  - HotbarPets
  - luckyblocks-sf
  - RedstoneConnector
  - PrivateStorage
  - SlimefunOreChunks
  - SlimyTreeTaps
  - SoulJars
  - CommandOverride
  - EmeraldEnchants2
  - QuickMarket
  - QuickSell
  - RankPrefixPlus
  - MoreTools
  - LiteXpansion
  - MobCapturer
  - SoundMuffler
  - ExtraTools
  - TranscEndence
  - Liquid
  - SFCalc
  - SlimefunWarfare
  - Slimy-Power-Suits
  - InfernalExpansion
  - FluffyMachines
  - SlimyRepair
  - InfinityExpansion
  - FoxyMachines
  - GlobalWarming
  - GlobiaMachines
  - DynaTech
  - GeneticChickengineering
  - HeadLimiter
  - BlockLimiter
  - SlimeXpansion
  - Barrels
  #- ClayTech
  - FNAmplifications
  - SimpleMaterialGenerators
  - Netheopoiesis
  - Networks
  - EMC2
  - Nexcavate
  - SimpleStorage
  - SimpleUtils
  - AlchimiaVitae
  - SlimeTinker
  - PotionExpansion
  - FlowerPower
  - Galactifun
  - ElementManipulation
  - CrystamaeHistoria
  - DankTech
  - DankTech2
  - Networks
  - VillagerUtil
  - MissileWarfare
  - SensibleToolbox
  - Endrex
  - Bump
  - FinalTech # For build 29- (included)
  - FinalTECH # For build 29+
  - SlimefunLuckyBlocks
  - FutureTech
  - DemonicExpansion
  - BedrockTechnology
  - SlimefunItemExpansion
  - SupplementalServiceableness
  - GuizhanCraft
  - Magmanimous
  - UltimateGenerators-RC27 # 不确定是否存在这个版本
  - UltimateGenerators # 构建站有
  - UltimateGenerators2 # 同上
  - CrispyMachine
  - DimensionTraveler
  - Chocohills
  - draconic # 疑似新版
  - DracFun # 疑似旧版(?
  - EzSFAddon # 疑似旧版
  - EzTech # 疑似新版
  - RandomExpansion
  - ExLimus
  - MoneyAndThings
  - VoidHarvesters
  - SlimyBees
  - GeneticManipulation
  - ObsidianExpansion
  - NotEnoughAddons
  - SlimeSec
  - EMCTech
  - RelicsOfCthonia
  - Supreme
  - DyeBench
  - MiniBlocks
  - SlimeHUD
  - SpiritsUnchained
  - Cultivation
  - Gastronomicon
  - SmallSpace
  - BetterReactor
  - BetterGenerator
  - VillagerTrade
  - SlimeFrame
  - AdvancedTech
  - Quaptics
  - CompressionCraft
  - CringleBosses
  - ThermalFun
  - FastMachines
  - MomoTech
  - EnchanterLimit
  - SlimeAE
  - SlimeChem
  - WilderNether
  - MapJammers
  - Cakecraft
  - SFMobDrops
  - Drugfun
  - SlimefunNukes
  - SlimeCustomizer
  - SlimefunAdvancements
  - HardcoreSlimefun
  - SfChunkInfo
  - SlimefunTranslation
  # Other plugins
  - PlaceholderAPI
  - NBTAPI
authors: [mmmjjkx]
description: An advanced Slimefun customize plugin
libraries:
  - org.graalvm.js:js-scriptengine:23.0.2
  - org.graalvm.js:js:23.0.2
  - org.graalvm.truffle:truffle-api:23.0.2
  - net.bytebuddy:byte-buddy:1.12.6
commands:
  rykenslimecustomizer:
    aliases: ["rsc"]
    permission: rsc.command.help
permissions:
  rsc.command:
    default: op
    children:
      rsc.command.help: true
      rsc.command.reload: true
      rsc.command.list: true
      rsc.command.reloadPlugin: true
      rsc.command.saveitem: true
      rsc.command.enable: true
      rsc.command.disable: true
      rsc.command.menupreview: true
      rsc.command.info: true
  rsc.command.help:
    default: op
  rsc.command.reload:
    default: op
  rsc.command.list:
    default: op
  rsc.command.reloadPlugin:
    default: op
  rsc.command.saveitem:
    default: op
  rsc.command.enable:
    default: op
  rsc.command.disable:
    default: op
  rsc.command.menupreview:
    default: op
  rsc.command.info:
    default: op
